apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server      = utf8mb4_0900_ai_ci
    sql_mode              = STRICT_ALL_TABLES
    default_time_zone     = +00:00
    innodb_flush_method   = O_DIRECT
    innodb_log_file_size  = 256M
    innodb_buffer_pool_size = 512M
