apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  namespace: eventos-peru
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 32006