apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventos-peru-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TU_ORG/TU_REPO.git
    targetRevision: main
    path: k8s/argocd/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: eventos-peru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
