apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventos-api
  namespace: eventos-peru
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Reescribe /<svc>/... -> /... en el backend (ej: /iam/docs -> /docs)
    nginx.ingress.kubernetes.io/rewrite-target: /$2

    # Redirección inteligente de /openapi.json según el Referer (sin tocar código)
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /openapi.json {
        set $dest "";
        if ($http_referer ~* "/iam/")          { set $dest "/iam/openapi.json"; }
        if ($http_referer ~* "/catalogo/")     { set $dest "/catalogo/openapi.json"; }
        if ($http_referer ~* "/proveedores/")  { set $dest "/proveedores/openapi.json"; }
        if ($http_referer ~* "/contratacion/") { set $dest "/contratacion/openapi.json"; }
        if ($dest = "") { return 404; }
        return 302 $dest;
      }

    # (Opcional) CORS/Rate limit comunes
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  rules:
    - host: eventos.emeday.inc
      http:
        paths:
          - path: /iam(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: iam-service
                port:
                  number: 80

          - path: /catalogo(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalogo-service
                port:
                  number: 80

          - path: /proveedores(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: proveedores-service
                port:
                  number: 80

          - path: /contratacion(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: contratacion-service
                port:
                  number: 80

  # tls:
  # - hosts: [eventos.emeday.inc]
  #   secretName: eventos-peru-tls
