apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventos-api
  namespace: eventos-peru
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Reescribe /<svc>/... -> /... en el backend (p.ej. /iam/docs -> /docs)
    nginx.ingress.kubernetes.io/rewrite-target: /$2

    # --- Swagger bajo subpaths sin tocar código ---
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Reemplaza en HTML y JS la ruta del OpenAPI para que use el prefijo actual (/iam, /catalogo, ...)
      sub_filter_once off;
      sub_filter_types text/html application/javascript;
      gunzip on;
      set $base "";
      if ($uri ~* "^/([^/]+)(/|$)") { set $base "/$1"; }
      sub_filter "/openapi.json" "$base/openapi.json";
    # ------------------------------------------------

    # Opcionales comunes
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  rules:
    - host: eventos.emeday.inc
      http:
        paths:
          - path: /iam(/|$)(.*)
            pathType: ImplementationSpecific
            backend: { service: { name: iam-service, port: { number: 80 } } }

          - path: /catalogo(/|$)(.*)
            pathType: ImplementationSpecific
            backend: { service: { name: catalogo-service, port: { number: 80 } } }

          - path: /proveedores(/|$)(.*)
            pathType: ImplementationSpecific
            backend: { service: { name: proveedores-service, port: { number: 80 } } }

          - path: /contratacion(/|$)(.*)
            pathType: ImplementationSpecific
            backend: { service: { name: contratacion-service, port: { number: 80 } } }

  # tls:
  # - hosts: [eventos.emeday.inc]
  #   secretName: eventos-peru-tls
